var World, zombie;

zombie = require("zombie");

World = function(callback) {
  callback();
};

World.browser = new zombie();

World.visit = function(url, callback) {
  this.browser.visit(url, callback);
};

module.exports.World = World;

// ---
// generated by coffee-script 1.9.2
